### ISSUE TITLE
Please add i686 iso with Openbox

### ISSUE THREAD

**Issue by jalfonsi** [ghostbsd/ghostbsd-build#24]
Please add a community build for i686 and Raspberry with a minimal GUI like Openbox for older hardware

**Comment by kraileth** [comment]
Anything i686 is very unlikely to happen. I do see the benefit of something like this and like to tinker with older hardware myself. In fact, I voted against GhostBSD dropping the i386 platform when that issue was discussed within the team. But there are valid reasons that lead to the opposite stance and I'm standing by the team decision: GhostBSD focuses more than ever on the incredibly useful features that ZFS provides (and the general consensus is: Don't uses ZFS on 32-bit platforms). Other than that, modern GhostBSD is built from TrueOS and the latter has dropped i386 support long ago when it even was a Qt-based desktop spin of FreeBSD under the name of PC-BSD. There literally isn't any support for i386 in the whole TrueOS infrastructure.

For the Raspberry Pi 3 and 4 there might be hope as arm64 (a.k.a aarch64) is a platform that some of the TrueOS devs seem to have interest in. So GhostBSD on newer Raspberrys might eventually happen.

I've been on hiatus for a while now and thus don't know the recent decisions. But there have been ideas of continuing a different spin of GhostBSD not based on TrueOS but on vanilla FreeBSD. That _could_ run on i386 platforms (but would of course not feature things like the OpenRC init system that's part of TrueOS - at least until FreeBSD makes a final decision on including it). Also it would be entirely unsupported as we don't have enough people running it seriously on that platform to even test it properly. The problem here is manpower: Somebody would have to step forward to do it. So if somebody reads this and thinks it's a good idea, go for it! Things like this are a great chance to learn things, BSD people in general (and the GhostBSD developers specifically) are nice and open - as time permits of course.
